### ISSUE TITLE
PsyPapersProject を次のステップに進めてくれる方, 募集します。

### ISSUE THREAD

**Issue by mentalistL** [manimanicocco/PsychPapers#157]
## 1. PsyPapersProject について
私が投稿しているこちらのGithubの投稿ページの正式名称は**PsyPapersProject**といいまして、
「**心理学や科学論文に興味を持ち、それを日常生活で使えるようになること**」をテーマに記事を執筆してきました。
2020年9月から始動し、現在まで1250本の論文を読み、150本ほど記事にして1年ほど続けてきました。

そしてこの度、この PsyPapersProject を次のステップに進めたいと思い、この記事を書きました。

## 2. 受動的な【読み手】から能動的な【書き手】へ
PsyPapersProject の次のステップは、
「**受動的な【読み手】から能動的な【書き手】が増えること**」です。
これにより**論文や科学について語る場をつくりたい**と考えております。

**これこそが私が Github を使う理由であり、「パレオな男」との最大の違いです**。

パレオな男の最大のメリットは、無料で、気軽に科学的な知識を得ることができる点だと思います。
もちろん、このGithubも同じです。

ただし、どうしても思うのです。

**・読むだけでは知識が身につかない。知識として覚えただけで、身体は何も身につけていない。**

・**ただ記事を読んで、覚えたつもりになってしまい、数日後には8割忘れている**

・**無料で情報を読めるから、情報に対して受動的になってしまい、情報を得ることが目的になってしまう**

・**テイカーという系（システム）に強制的に組み込まれる**

こういった現象は書き手になっても経験することはあります。
しかし、私も長年「パレオな男」を読むだけの一読者でしたが、書き手になることで変わってこともあります。

・**一次ソースにアクセスするようになった**

・**英語が大の苦手だったが、抵抗なく読むようになった**

・**情報に対して、「本当にそうなのか？」と疑うクセがついた**

・**紹介されている内容は「ざっくりと大事なところや結論」をまとめてくれるのでわかりやすいが、
「厳密に言うと、、」というと若干結論が違うこともあり、解釈の都合やわかりやすさ、読みやすさを優先することで若干のズレが生じることがある**

・**記事を読んだ人とその論文について語ることで、新しい発見があったり、記憶に残りやすくなった**

こういった変化がありました。つまり何が言いたいのかというと、
>「**読み手」と「書き手」では、知識・情報に対しての向き合い方、感度、記憶の定着率など、根本的に異なるということ**

です。
もちろん、情報・知識を得ることを目的にすることもかまいませんし、「情報・知識を得るだけである」ことが悪いといっているわけでもありません。
純粋に読み手と書き手は根本的に立場やマインド、感度など、様々な要素が変わるということです。

## 3. Github である理由
**ブログや書籍というシステムは、読み手になる人が99％の世界**でした。

**しかし、このGithubは違います**。

Githubというのはもともと複数人の開発において使用されてきたツールなんだそうで、
Githubの本来の形は
「**複数の人がGithubというプラットフォーム上で、情報のアップデートや意見の交換を行うことができること**」
なのです。
現在の形は私という個人だけがひとりで情報を更新している形ですが、この形態では個人ブログやnoteでも良いのです。
先程も述べましたが、これが「**パレオな男」で読むだけのこれまでとの最大の違いです**。
**Githubを用いるということは、読み手から書き手、利用者から開発者になるということでもある**のです。

これまではフォロワーさんも少なく、読者もほとんどいませんでした。
そのため書き手が増えること自体、可能性がありませんでした。
しかし今回、鈴木祐さんがシェアしてくれたことで、たくさんの人に見ていただくことができました。
やっと、Github本来の形に近づくための芽が生えたと思っています。
この芽を咲かせるためには、書き手の存在が不可欠なのです。

## 4. 実際、書くことは楽なことではない
当たり前のことですが、書くことも楽なことではありません。
鈴木さんは「無」を出版される際に、何百本読んで一本使える論文があるかないか、ということをお話していました。

私自身は日本語の論文ですら抵抗があったので、英語論文を読む前は日本語論文を200本ほど読んで慣らしましたし、
はじめのころは1本記事を書くのに一日4時間書いたり読んだりして、2～3日かかりました。
また、100本以上書いても誰からも称賛されません。
いいねもつかないこともよくあります。
お金にもなりません。
そう、メリットなどほとんどありません。

それを続けてきて、PsyPapersProjectの創設者であるmanicoさんと鈴木祐さんに偶然ご縁があり、鈴木さんにシェアしていただくきっかけになりましたが、縁がなければ日の目を浴びることもありませんでした。

つまり何がいいたいかというと、
・**書き手になったからといって、こちらからは何もメリットを提示できないということ**

・**論文の読み方講座や、書き方講座などを開くことはしないので、自分で試行錯誤していくしかないということ**

・**楽しみややることの価値は自分で見つけ出すしかないということ**

こういうことです。慣れないうちは苦痛ですし、挫折することもあるでしょう。

**書くメリットがないなら書くわけないだろう**！と思う方がほとんどだと思います。仰る通りです。

ただそれでも
・**このプロジェクトに参加してみたい**

・**受動的な読み手を卒業し、書き手という立場を体感したい**

・**英語論文を読めるようになりたい**

・**ただ得るだけの立場から、提供するスタンスに立ちたい**

・**メリットの無い過酷な環境でも続けるマインドセットを身に着けたい**

こんな方はぜひお声がけください。一緒にPsyPapersProject を大きくしていきましょう。

**最後に**。
私が今回この募集をかけてみたのは、情報を得るだけの立場と、自分から取りに行く立場、つまり自分から提供する立場になることで、物事を捉える視点が180度変わることを知ったからです。そのことをぜひ体感してほしいのです。
PsyPapersProject の次のテーマは、このGithubのページが１つの体験になること。
実際に触って、手を動かし、思考を動かすこと。ハードルは高く感じるかもしれません。
でも、この体験ができるのはこのGithubだけ、唯一無二です。

私の550人のフォロワーさんで実際に書き手になる人は何人いるでしょうか。
PsyPapersProject への挑戦、楽しみにしております。

## 5. 注意事項（必ずお読みください）
・**こちらはコミュニティではありません。またコミュニティにすることもありません。
コミュニティという概念が発生した時点で、コミュニティが個人に与えるモチベーションや人間関係などに影響を与えるからです。あくまでも、共通点を持った個人が、能動的に集い、話し合える場であることが目的です**。

・**今まで通り読み手でいることも大歓迎です。今回の募集は、書き手になることのメリットがほとんどないため、
100％内発的動機がない限り続けることができないと思っています。また、募集の結果、書き手が０人であることも想定しています。やる気はなくても構いません。ただ、続けたいという意志があれば十分ですし、続けられなくても誰も攻めませんし、誰も気にしません。挫折もOKです**。

・**資格はいりません。他人を傷つけるような投稿や、他者を尊重しない行動、論文著者、サマリー投稿者への暴言等は禁止**。

・**投稿頻度は自由。週1回でもいいし、月1回でも構いません**。

・**わからないことがあればいつでもご質問ください**。

**Comment by keiya-k** [comment]
こんにちは。
データサイエンスと金融をシドニー大学で学んでいる19歳です。

参加したいです。

**Comment by mentalistL** [comment]
> こんにちは。 データサイエンスと金融をシドニー大学で学んでいる19歳です。
> 
> 参加したいです。

**Comment by mentalistL** [comment]
@KeiYa-K 
ご連絡ありがとうございます、PsyPapersProjectで記事を書いている加藤と申します。
もしよろしければ一度ご挨拶とご説明も兼ねてお話してみたいのですが、
もし私のTwitterから知っていただいているようであればDMを開いておくのでメッセージいただけると嬉しいです。

よろしくお願いいたします。

**Comment by y-nakazaki-ai** [comment]
いつも勉強させていただいてます。
英語がまるっきり分からないので、
まだまだ論文を読み解いたり出来るほどの
読解力はありませんが、将来的に出来るようになれたらと思い登録してみました。
時折気になった記事があったらコメントを残そうと思いますのでよろしくお願いします。
